{"uuid": "95a294f7-f5c5-4651-a86d-b54498cb95c7", "children": ["d4912f66-0473-4bfe-b477-4756531152df"], "befores": [{"name": "open_baidu", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"D:\\python3.8\\python-3.8.2\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python3.8\\python-3.8.2\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python3.8\\python-3.8.2\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Working_Python\\selenium_pytest\\TestCase\\test_search.py\", line 18, in open_baidu\n    search.get_url(ini.url)\n  File \"D:\\Working_Python\\selenium_pytest\\page\\webpage.py\", line 27, in get_url\n    self.driver.maximize_window()\n  File \"D:\\python3.8\\python-3.8.2\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"D:\\python3.8\\python-3.8.2\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python3.8\\python-3.8.2\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1640681549971, "stop": 1640681550139}], "start": 1640681549971, "stop": 1640681550872}